### PR TITLE
Feat/project structure

### PR DESCRIPTION
**Pull request by levinzonr**
Sets up the basic project structure

# Two top-level packages

`core` - Package that contains things that are not related to the domain and/or business logic of the app. This may include different extension functions on basic Kotlin/other core classes, utitlities, shared ui components, and Base classes. Basically, all the stuff that can be re-used across all of our projects with minor modifications when needed

`features` - package with all the features related to the app, where a feature is a set of components that are used to fulfill some business requirement. Example structure of the `feature` package
```kotlin
login/
 - data // data sources (api, database, other), entities, dtos, extensions (if any)
 - domain
   -  usecase 
   -  repository
   -  models
 - ui  //fragments, viewModels, composables, can be multiple screens or none
 - injection // if required
```

This way every feature, when used correctly, will be a component that can be easily extracted into a separate module if needed

# Questions
## Do we need another top-level `shared` package?
The idea of `shared` is to group some features that are used across the app, for example `analytics` feature or `nstack`.

For a small application I think only having a singular `features` package should be enough, but maybe we should mention it in the Documentation somewhere that there is this option 

```kotlin
- core
- features
- shared
- App.kt
```

### CODE REVIEW

**Comment by johsoe** [comment]
> The idea of shared is to group some features that are used across the app, for example analytics feature or nstack.

That sounds like features to me. Wouldn't shared UI components be a better example? Theming? 

So `core` would be piping and `shared` would be more UI focused. 

Suggestion: should we try only having `core` and then have a `components` top level? Or should it be a feature on its own?

**Comment by johsoe** [comment]
>  - injection // if required

We would try to enforce a single shared injection point, right? So potentially in a multi module setup, the app module would handle all custom DI with Hilt handling everything else on a feature level.

**Comment by johsoe** [comment]
>  login/
>  - data // data sources (api, database, other), entities, dtos, extensions (if any)
>  - domain
>    -  usecase 
>    -  repository
>    -  models

I would suggest:
Domain.models = domain.entities
Data.dtos

Would this structure not make it harder for OpenAPI/Swagger to generate models?

**Comment by levinzonr** [comment]
Latest updates:
- all API related models are now have DTO suffix
- Apply mapping of DTOs in the same file as the extension
- use *storage* in *api* packages in data

**Review by johsoe — APPROVED** [review]

**Pull request merged**
