### PR TITLE
Navigation proposal

### PR DESCRIPTION
**Pull request by alperbry**

### CODE REVIEW

**Comment by Tgo1014** [comment]
Why use this “wrapper” around the navigation library instead of the nav lib directly?

**Comment by alperbry** [comment]
View --- ViewModel --- UseCase --- ...
                      |
                      |
                  Router
                  
The diagram after the pr will be like above. Fragments will observe ViewModels which implement NavigationOwner and reacts by events emitted by router. The events will be emitted as NavigationModels which is simply works like a wrapper for Navigation Component and can be directly created using NavDirections generated by safeArgs.

**Comment by alperbry** [comment]
> Why use this “wrapper” around the navigation library instead of the nav lib directly?

The implementation aims to seperate navigation logic from view layer. Since the navigation component is tightly coupled to Fragment, implementing something that observes navigation events and executes navigation component methods made sense. Furthermore, the navigation implementation on features are not tightly coupled to a navigation library anymore (which was not the main goal but also a good thing).

**Comment by levinzonr** [comment]
Closing
Reason: **stale PR**

**Pull request closed without merging**
